import Head from "next/head";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Yo</h1>
    </div>
  );
}
